// <auto-generated />
using Mango.Services.ProductAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Mango.Services.ProductAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240212190648_initialProductTable")]
    partial class initialProductTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mango.Services.ProductAPI.Model.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryName = "Dinner",
                            Description = "Nice Good",
                            ImageUrl = "https://placehold.co/603x403",
                            Name = "Samosa",
                            Price = 1225.0
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryName = "Dinner",
                            Description = "Nice Good",
                            ImageUrl = "https://placehold.co/602x402",
                            Name = "Alexoid",
                            Price = 75.0
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryName = "Launch",
                            Description = "Nice Good",
                            ImageUrl = "https://placehold.co/601x401",
                            Name = "GoldFish",
                            Price = 45.0
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryName = "Dinner",
                            Description = "Nice Good",
                            ImageUrl = "https://placehold.co/600x400",
                            Name = "Kesstel",
                            Price = 25.0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
